apiVersion: apps/v1
kind: Deployment
metadata:
  name: cl4p-tp-slash-commands-deployment
  labels:
    app: cl4p-tp-slash-commands
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cl4p-tp-slash-commands
  template:
    metadata:
      labels:
        app: cl4p-tp-slash-commands
    spec:
      containers:
        - name: cl4p-tp-slash-commands
          image: flaviogf/cl4p-tp-slash-commands
          imagePullPolicy: Never
          envFrom:
          - configMapRef:
              name: cl4p-tp-slash-commands-config-map
          ports:
            - containerPort: 8080
